# Configurations for python built-in logging
logging:
  level: info
  stream-handler: console

# Kafka topics
topics:
  clients-locations: &clients-locations-topic clients.client-routes-locations.export
  clients-push: &clients-push-topic adv-push.actual-adv.export

# Data paths
data:
  adv-campaign-data: &adv-campaign-data s3a://data-ice-lake-05/master/data/source/spark-static-stream/adv-campaign-data
  clients-locations-data: &clients-locations-data s3a://data-ice-lake-05/master/data/source/spark-static-stream/clients-locations

# Apps configurations
apps:
  spark:
    app-name: streaming-app
    is-debug: false
    clients-locations-topic: *clients-locations-topic
    clients-push-topic: *clients-push-topic
    adv-campaign-data: *adv-campaign-data
    checkpoints-location: s3a://data-ice-lake-05/master/data/source/spark-streaming-checkpoints

  producer:
    output-topic: *clients-locations-topic
    input-data-path: *clients-locations-data

  generator:
    output-data-path: *adv-campaign-data
