logging:
  python:
    level: debug
    stream-handler: console

spark:
  adv-campaign-data: s3a://data-ice-lake-05/master/data/source/spark-static-stream/adv-campaign-data
  topic:
    input: test.in
    output: test.out

producer:
  topic: test.in
  data-path: s3://data-ice-lake-05/master/data/source/spark-static-stream/clients-locations/part-0000.gz.parquet

data:
