version: '3.8'

x-spark-common: &spark-common
  build: 
    dockerfile: docker/spark/Dockerfile
  environment: 
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=2G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark
    # More environment variables natively supported by Apache Spark
    # can be found here -> https://spark.apache.org/docs/latest/spark-standalone.html#cluster-launch-scripts
  volumes:
    - ./src:/code/src
    - ./jobs:/code/jobs
    - ./utils:/code/utils
    - ./pyproject.toml:/code/pyproject.toml
    - ./poetry.lock:/code/poetry.lock
    - ./config/log4j2.properties:/opt/bitnami/spark/conf/log4j2.properties

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    depends_on:
      - spark-master

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    ports:
      - "8082:8081"
    depends_on:
      - spark-master

  spark-worker-3:
    <<: *spark-common
    container_name: spark-worker-3
    ports:
      - "8083:8081"
    depends_on:
      - spark-master

# https://github.com/bitnami/containers/tree/main/bitnami/kafka
  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://158.160.78.165:9092
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094 
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://158.160.6.228:9094
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT





