install-unified-agent: "0"
ssh-keys: leonide:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMMPrWVK4wsS7Z3s7cqh/11kryCS+i/jR0EIB1RXEmuThO0lACv2yS6zMPtNFGHGepPsvsC8Zjszu0Ntoe6kW/VOLtc7et2NBXVyfW/ZO0ttpySDMjuhLy+2uchv98vDvtnZ5fI1/03PSkmnuH+NVImLJK3E4Tc30G4JkfNkW5u7px8AjANtoxYJ5/wMCh5M7pgQm3Wro79gdTwTuZlSt9x629UoURnLEtY3mr6wQRfLySDBjbz7hqPrVUhzU0iaZWQubY9cGGx9SWg6Oaje5EzBFj/5Xs4/Ue2bIlEQv0QIgc2RiQR0mTTweCVc11NeER66z9faQBCSMo3atUSgnLqovTyxx+Zezkdf4qPc5IoY73AAO6rQUgmCN8/9fWlc8ZtPKqR5Sdsi7yMoortrO5u2QkLJKZTVBWuH5ef9f2Lc9Zc0BaveipLuhhjxH9ItvDZO5mmyZUFXMgrEnSntW79eDBaDoePb1mawrDWFjrDZJhSnuTlUHxOrpn1aweeGk7dHe+OXLH01m3Xz0i7xboVnp/nnFywecHvfd+Gh5IEAhebOmynwxx4NFqm7pzQoSLB+nliSqe2KJehyQtj56BqxsMnKMXbOrR9QCSukNaHCr33gHGFADYgKLD1yeKEZRoXjoaIAE7RcTLiJE1dxWt2esfvlLbxH0JAiuzhSOKQQ== leonide@MacBook-Pro-Leonide.local
user-data: |-
  #cloud-config
  datasource:
    Ec2:
    strict_id: false
  ssh_pwauth: no
  users:
  - name: leonide
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDMMPrWVK4wsS7Z3s7cqh/11kryCS+i/jR0EIB1RXEmuThO0lACv2yS6zMPtNFGHGepPsvsC8Zjszu0Ntoe6kW/VOLtc7et2NBXVyfW/ZO0ttpySDMjuhLy+2uchv98vDvtnZ5fI1/03PSkmnuH+NVImLJK3E4Tc30G4JkfNkW5u7px8AjANtoxYJ5/wMCh5M7pgQm3Wro79gdTwTuZlSt9x629UoURnLEtY3mr6wQRfLySDBjbz7hqPrVUhzU0iaZWQubY9cGGx9SWg6Oaje5EzBFj/5Xs4/Ue2bIlEQv0QIgc2RiQR0mTTweCVc11NeER66z9faQBCSMo3atUSgnLqovTyxx+Zezkdf4qPc5IoY73AAO6rQUgmCN8/9fWlc8ZtPKqR5Sdsi7yMoortrO5u2QkLJKZTVBWuH5ef9f2Lc9Zc0BaveipLuhhjxH9ItvDZO5mmyZUFXMgrEnSntW79eDBaDoePb1mawrDWFjrDZJhSnuTlUHxOrpn1aweeGk7dHe+OXLH01m3Xz0i7xboVnp/nnFywecHvfd+Gh5IEAhebOmynwxx4NFqm7pzQoSLB+nliSqe2KJehyQtj56BqxsMnKMXbOrR9QCSukNaHCr33gHGFADYgKLD1yeKEZRoXjoaIAE7RcTLiJE1dxWt2esfvlLbxH0JAiuzhSOKQQ== leonide@MacBook-Pro-Leonide.local
